version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # Porta de conexão padrão do RabbitMQ
      - "15672:15672"  # Porta da interface de gerenciamento do RabbitMQ
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq  # Volume para persistir os dados do RabbitMQ

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "1433:1433"
    networks:
      - sqlserver_network
    volumes:
      - sqlserver_data:/var/opt/mssql
      - /var/lib/desktop-containerd:/var/lib/desktop-containerd
      - /var/lib/containerd:/var/lib/containerd
      - /var/run:/var/run

networks:
  sqlserver_network:
    driver: bridge

volumes:
  sqlserver_data:
